### ISSUE TITLE
Proposals for changes (typertools 1.4.4)

### ISSUE THREAD

**Issue by NatsukiRem** [Swirt/typertools-src#28]
**1) The new build typertools' version (1.4.4) does not work because of wrong names.**

_What it needs to fix it:_
Change the name of the _app-scr_ folder to _app_

(and that is not the only problem with this built - this built may does not wok at all)

\

**2) Incorrect caption - photoshop error**

On the official site with the project (**https://swirt.github.io/typertools/**) is a folder for quick download (**Download ZIP 1.4.4**). After installing photoshop gives an error: "incorrect signature". 

\

**3) Unknown error during installation**

For some users, including me, the typertools tool just shows a gray or white background after installation in the photoshop window.

_What it needs to fix it:_
To get this program to work I had to cross two builds: from the official site (**https://swirt.github.io/typertools/**) and from the github project site (**https://github.com/Swirt/typertools-src**). Namely I replaced the folders in '_typertools-src_' with the same folders in '_typertools-1.4.4_'.

**Comment by Swirt** [comment]
There is no such problem. Github.io contains the most current version of the build, src files should not be used in the work.
The problem with the signature is caused by the fact that Photoshop wasn't switched to developer mode, which should happen when the installer launches. 
The problem with the white screen could also be caused by the fact that you are using a portable/lightened build of Photoshop that has removed the components you need for the extension to work.
